### ISSUE TITLE
Redesign landing page

### ISSUE THREAD

**Issue by hugo-sid** [kluctl/www-kluctl.io#72]
## Description

- The current landing page does not posses a professional look.
- Showing 13 features at once can be overwhelming for a visitor
- Regarding the Kluctl demo video on the hompage:

    - The video with two different windows can be quite confusing for a visitor initially
    - Loading ~ 19 MB video in the above the fold can be a bad UX
    - Ensure that there is no video content above the fold on the website; prioritize static elements for the initial user experience
    - Either relocate it to a later section on the homepage or use a GIF if necessary

## Tasks

- [x] Design a new layout for homepage in Figma
- [x] Preserve the current website structure, links
- [x] Add a recent blog section on the homepage to show latest updates/developments 
- [x] Add a GitHub icon in the header - visitor can checkout GitHub link immediately
