### ISSUE TITLE
Change navbar styling

### ISSUE THREAD

**Issue by hugo-sid** [kluctl/www-kluctl.io#79]
## Description

The navbar (on left) has a lot of icons which aren't required. The indentation of nav items is sufficient to give idea about various sections/pages. 

The theme doesn't allow navigating to list pages. The existing Kluctl documentation has lots of content in list pages. 

## Tasks

- [x] Remove icons
- [x] Convert list page buttons to links, so that a visitor can navigate to list pages
- [x] Decrease the height of navbar items
- [x] Decrease the width of the navbar if possible
