### ISSUE TITLE
Change the documentation accent colors

### ISSUE THREAD

**Issue by hugo-sid** [kluctl/www-kluctl.io#81]
## Description

Change the documentation accent colors to suit Kluctl brand colors.

The theme has a predefined set of accent colors, which are:  blue (default), green, red, yellow, emerald, cardinal, magenta, cyan.

Emerald is pretty close to Kluctl brand colors. 

## Tasks

- [ ] Start with emerald & see if it is a good fit
- [ ] Modify the color variables if required
- [ ] Check colors for dark mode
- [ ] Check color compliance with accessibility standards

## Resources

- https://hslpicker.com/ - HSL color picker
- https://colourcontrast.cc/ - Given two colors (background & foreground) this website shows AA Large, AAA Large, AA Normal AAA Normal accessibility compliance. 

## Notes

- How HSL works: pick a Hue from 0 to 360 and with saturation at 100 and luminosity at 50 and you'll have the purest form of that color. Reduce the saturation and you move towards gray. Increasing the luminosity moves you towards white, decreasing it moves you towards black.
- The colors must pass all accessibility levels, both for light & dark mode.
